name: Sync images to ACR

on:
  workflow_dispatch:
    inputs:
      HUB_SRC:
        required: true
        default: "docker.io"
        description: "仓库"
      HUB_IMAGE:
        required: true
        default: ""
        description: "用户空间/镜像名:标签"
      ACR_IMAGE:
        required: true
        default: ""
        description: "ACR 中的 用户空间_镜像名:标签"
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  ACR_REGISTRY: "registry.cn-shanghai.aliyuncs.com"
  ACR_NAMESPACE: "aceslup"
  ACR_IMAGE_FULLNAME: "${ACR_REGISTRY}/${ACR_NAMESPACE}/${{ github.event.inputs.HUB_SRC }}_${{ github.event.inputs.ACR_IMAGE }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: "registry.cn-shanghai.aliyuncs.com"
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: false

    # 使用 skopeo 工具将镜像同步到阿里云个人仓库中
    - name: Use Skopeo Tools Sync images to ACR
      run: |
        skopeo copy \
          docker://${{ github.event.inputs.HUB_SRC }}/${{ github.event.inputs.HUB_IMAGE }} \
          docker://${ACR_IMAGE_FULLNAME}

    - name: How to pull image
      run: |
        echo "docker pull ${ACR_REGISTRY}/${{ github.event.inputs.ACR_IMAGE }}"
