name: Sync DockerHub images to ACR

on:
  workflow_dispatch:
    inputs:
      HUB_IMAGE:
        required: true
        default: ""
        description: "DockerHub 中的 仓库/镜像名:标签"
      ACR_IMAGE:
        required: true
        default: "aceslup/docker.io_"
        description: "ACR 中的 仓库_镜像名:标签"
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  HUB_SRC: "docker.io"
  ACR_REGISTRY: "registry.cn-shanghai.aliyuncs.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: "registry.cn-shanghai.aliyuncs.com"
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: false

    # 使用 skopeo 工具将镜像同步到阿里云个人仓库中
    - name: Use Skopeo Tools Sync DockerHub images to ACR
      run: |
        skopeo copy \
          docker://${HUB_SRC}/${{ github.event.inputs.HUB_IMAGE }} \
          docker://${ACR_REGISTRY}/${{ github.event.inputs.ACR_IMAGE }}

    - name: How to pull image
      run: |
        echo "docker pull ${ACR_REGISTRY}/${{ github.event.inputs.ACR_IMAGE }}"
  
